[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express", "serverless-http"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true 